# Generated by Django 5.1.3 on 2024-12-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='description',
        ),
    ]
